# Dependabot configuration to keep dependencies up to date.
# Documentation: https://docs.github.com/code-security/dependabot

version: 2
updates:
  # Python package updates for this project.
  - package-ecosystem: "pip" # Specifies the Python package manager (pip)
    directory: "/" # Root directory where the requirements.txt file is located
    schedule:
      interval: "weekly" # Set Dependabot to check for updates every week
      day: "monday" # Dependabot will update dependencies every Monday
      time: "08:00" # Time of the day to check for updates (UTC)
    ignore:
      # Specify any dependencies to ignore for updates (e.g., pinned or managed externally).
      - dependency-name: "some-package"
        versions: ["1.x"]

  # GitHub Actions updates (optional).
  - package-ecosystem: "github-actions" # Keeps GitHub Action dependencies up to date
    directory: "/" # GitHub Actions configuration is typically in the root directory
    schedule:
      interval: "weekly" # Check for updates weekly
      day: "monday"
      time: "08:00"
